#unbind C-b
set-option -g prefix C-a

# Scroll Fix for alacritty, Issue #1194 on alacritty
# mouse on fixes this, use below if you want to disable faux scroll and disable mouse
#set -ga terminal-overrides ',*256color*:smcup@:rmcup@'
setw -g mouse on
# if you want middle mouse, paste below or shift + middle mouse, had set mouse off to get this behaviour
bind -T root MouseDown2Pane run -b "xclip -o | tmux load-buffer - && tmux paste-buffer -s ' '"

#set-option -g prefix Super_L

set -g base-index 1
setw -g aggressive-resize on
set -g status-bg black
set -g status-fg white
set -g status-left "  "
#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
#set -g status-right "#[fg=green]#H"
#bind-key M-a last-window
bind-key tab last-pane



set -g default-command "/bin/zsh"
#set -g default-shell "/bin/bash"


setw -g mode-keys vi
bind-key | split-window -h
bind-key - split-window -v
bind-key enter new-window
unbind c

bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# [ to start  , ] to paste this is called scrollback mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi b send-keys -X rectangle-toggle
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary"
#
bind v setw synchronize-panes
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
#run -b '~/.tmux/plugins/tpm/tpm'

bind-key r source-file ~/.tmux.conf
bind-key u attach -t base
